sayilar=[]
bir=input("1. Sayıyı giriniz:")
iki=input("2. Sayıyı giriniz:")
uc=input("3. Sayıyı giriniz:")
dort=input("4. Sayıyı giriniz:")
bes=input("5. Sayıyı giriniz:")
print(sayilar)
sayilar.append(bir)
sayilar.append(iki)
sayilar.append(uc)
sayilar.append(dort)
sayilar.append(bes)
sayilar.sort()
print(sayilar[4])